// Generated by Wrangler by running `wrangler types` (hash: 869ac3b4ce0f52ba3b2e0bc70c49089e)
// Runtime types generated with workerd@1.20250823.0 2024-11-11
declare namespace Cloudflare {
  interface Env extends Record<string, undefined> {
    StateNonceKV: KVNamespace;
    CodeNonceKV: KVNamespace;
  }
}
interface Env extends Cloudflare.Env {
  DOMAIN?: string;
  ISSUER_BASE_URL: string;
  JWT_PRIVATE_KEY_PEM: string;
  JWT_PUBLIC_KEY_JWK: string;
  JWT_KEY_ID: string;
  ALLOWED_REDIRECT_URIS?: string;
  ALLOWED_CLIENT_IDS?: string;
  STATE_PREFIX?: string;
  ISSUER_AUTH_PATH?: string;
  ISSUER_TOKEN_PATH?: string;
  ISSUER_USERINFO_PATH?: string;
  ISSUER_JWKS_PATH?: string;
  ISSUER_CALLBACK_PREFIX?: string;
  LARK_MODE?: string;
  DEBUG_PAGE?: string;
  APP_LARK_ID?: string;
  APP_LARK_SECRET?: string;
  LARK_FUNCTIONAL_ROLE_IDS?: string;
  DEFAULT_LOCALE?: string;
}
